import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

const DEFAULT_OUTPUT_PATH = join(
  process.cwd(),
  "src/language/treesitter/wasm-data.generated.ts",
);

export type GenerateWasmDataOptions = {
  outputPath?: string;
};

const resolvePackagePath = (packageName: string, relativePath: string) => {
  const packageJsonPath = require.resolve(`${packageName}/package.json`);
  return join(dirname(packageJsonPath), relativePath);
};

const createGeneratedModule = (
  treeSitterWasmBase64: string,
  stanGrammarWasmBase64: string,
) => `// This file is generated by scripts/generate-wasm-data.ts.
// Do not edit manually.

export const TREE_SITTER_WASM = ${JSON.stringify(treeSitterWasmBase64)};

export const STAN_GRAMMAR_WASM = ${JSON.stringify(stanGrammarWasmBase64)};
`;

export const generateWasmData = async ({
  outputPath = DEFAULT_OUTPUT_PATH,
}: GenerateWasmDataOptions = {}) => {
  const treeSitterWasmPath = resolvePackagePath(
    "web-tree-sitter",
    "web-tree-sitter.wasm",
  );
  const stanGrammarWasmPath = resolvePackagePath(
    "@wardbrian/tree-sitter-stan",
    "grammars/stan/tree-sitter-stan.wasm",
  );

  const [treeSitterWasm, stanGrammarWasm] = await Promise.all([
    readFile(treeSitterWasmPath),
    readFile(stanGrammarWasmPath),
  ]);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(
    outputPath,
    createGeneratedModule(
      treeSitterWasm.toString("base64"),
      stanGrammarWasm.toString("base64"),
    ),
  );
};

if (import.meta.main) {
  await generateWasmData();
}
