name: Build and Release Executables

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create Github Release
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$tag" \
            --generate-notes \
            --draft
            
  build_artifact:
    needs: [create_release]
    name: ${{ matrix.os }}/${{ matrix.arch }}/${{ github.ref_name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: ubuntu-latest 
            platform: linux
            arch: x86_64
          - os: ubuntu-24.04-arm 
            platform: linux
            arch: arm64
          - os: macos-15-intel
            platform: macos
            arch: x86_64
          - os: macos-15
            platform: macos
            arch: aarch64
          - os: windows-latest 
            platform: windows
            arch: x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --verbose

      - name: Set version number
        id: version
        run: |
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build and compile executable
        run: |
          mkdir -p bin
          bun run build:binary

      - name: Set artifact paths
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          BASE="stan-ls-${VERSION}-${{ matrix.platform }}-${{ matrix.arch }}"
          echo "ZIP_PATH=./bin/${BASE}.zip" >> $GITHUB_ENV
          if [[ "${{ matrix.os }}" == *windows* ]]; then
            echo "EXE_PATH=./bin/${BASE}.exe" >> $GITHUB_ENV
          else
            echo "EXE_PATH=./bin/${BASE}" >> $GITHUB_ENV
          fi

      - name: Zip and rename executable
        run: |
          if [[ "${{ matrix.os }}" == *windows* ]]; then
            7z a "${{ env.ZIP_PATH }}" ./bin/stan-language-server.exe
            mv ./bin/stan-language-server.exe "${{ env.EXE_PATH }}"
          else
            zip -j "${{ env.ZIP_PATH }}" ./bin/stan-language-server
            mv ./bin/stan-language-server "${{ env.EXE_PATH }}"
          fi

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ steps.version.outputs.version }}" \
            "${{ env.ZIP_PATH }}" \
            "${{ env.EXE_PATH }}" \
            --repo="$GITHUB_REPOSITORY"