name: End-to-End Tests

on:
  push:
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun build:binary

    - name: Setup Python
      uses: actions/setup-python@v6

    - name: Install dependencies
      run: pip install pytest pytest-lsp

    - name: Run tests
      run: pytest tests --verbose
